# Generated by Django 5.0.7 on 2024-07-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_stu_city_student_city_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
