# Generated by Django 5.0.7 on 2024-07-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=70)),
                ('dep_desc', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_contact', models.IntegerField(max_length=70)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.department')),
            ],
        ),
    ]
