# Generated by Django 5.0.7 on 2024-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_Name', models.CharField(max_length=70)),
                ('Stu_Email', models.EmailField(max_length=254)),
                ('Stu_Contact', models.IntegerField()),
                ('Stu_City', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
