# Generated by Django 5.0.7 on 2024-07-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Vaishu'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
