# Generated by Django 5.0.7 on 2024-07-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Vaishu',
        ),
    ]
