# Generated by Django 5.0.7 on 2024-07-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
