# Generated by Django 5.0.7 on 2024-07-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Vaishu',
        ),
    ]
